### ISSUE TITLE
ERROR - install from source code

### ISSUE THREAD

**Issue by omergunal** [mitre/adversary#11]
I wrote this command before run caldera.py
System: ubuntu 16.04
```
echo "replSet = caldera" >> /etc/mongodb.conf
```

```
python3.5 caldera.py 
INFO:app.engine.database:Performing first time replication set initialization on MongoDB
Traceback (most recent call last):
  File "/root/caldera/caldera/app/engine/database.py", line 51, in initialize
    a = next(oplog.find().sort('$natural', pymongo.DESCENDING).limit(-1))['ts']
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 1197, in next
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "caldera.py", line 24, in <module>
    server.run(debug=debug)
  File "/root/caldera/caldera/app/server.py", line 111, in run
    database.initialize(settings['database']['key'], settings['database']['host'], settings['database']['port'])
  File "/root/caldera/caldera/app/engine/database.py", line 54, in initialize
    _setup_replica_set(host, port)
  File "/root/caldera/caldera/app/engine/database.py", line 33, in _setup_replica_set
    c.admin.command("replSetInitiate", config)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/database.py", line 614, in command
    codec_options, session=session, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/database.py", line 514, in _command
    client=self.__client)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/pool.py", line 579, in command
    unacknowledged=unacknowledged)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/network.py", line 150, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: server is not running with --replSet
```

**Comment by ArtificialErmine** [comment]
This issue appears to be dependent on design decisions only present in older versions of Caldera. If the issue persists after updating to the most recent iteration, feel free to re-open this issue or create a new one. Until then, I'm closing this due to inactivity and age.
