### ISSUE TITLE
Adversary GUI not working

### ISSUE THREAD

**Issue by AngryOnigiri** [mitre/adversary#31]
I use Ubuntu 19.04 and I can start server.py without any errors but when I try to access the adversary GUI on the interface I get a 500 error and following output:

ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp_session/__init__.py", line 152, in factory
    response = await handler(request)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 96, in impl
    return await handler(request)
  File "/home/ubuntu/Desktop/caldera/app/service/auth_svc.py", line 68, in wrapped_function
    return await target_function(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp_jinja2/__init__.py", line 91, in wrapped
    context = await coro(*args)
  File "/home/ubuntu/Desktop/caldera/plugins/adversary/app/service/adversary_api.py", line 238, in planner
    techniques=con.get_techniques(),
  File "/home/ubuntu/Desktop/caldera/plugins/adversary/app/database/dao.py", line 24, in get_techniques
    return self.db.get_techniques(ids)
  File "/home/ubuntu/Desktop/caldera/plugins/adversary/app/database/mongo.py", line 59, in get_techniques
    return [self._map_technique(x) for x in self._query('technique', ids)]
  File "/home/ubuntu/Desktop/caldera/plugins/adversary/app/database/mongo.py", line 59, in <listcomp>
    return [self._map_technique(x) for x in self._query('technique', ids)]
  File "/home/ubuntu/.local/lib/python3.7/site-packages/pymongo/cursor.py", line 1189, in next
    if len(self.__data) or self._refresh():
  File "/home/ubuntu/.local/lib/python3.7/site-packages/pymongo/cursor.py", line 1104, in _refresh
    self.__send_message(q)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/pymongo/cursor.py", line 982, in __send_message
    helpers._check_command_response(first)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/pymongo/helpers.py", line 132, in _check_command_response
    raise NotMasterError(errmsg, response)
pymongo.errors.NotMasterError: node is not in primary or recovering state

**Comment by douwanhu** [comment]
> I use Ubuntu 19.04 and I can start server.py without any errors but when I try to access the adversary GUI on the interface I get a 500 error and following output:
> 
> ERROR:aiohttp.server:Error handling request
> Traceback (most recent call last):
> File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 390, in start
> resp = await self._request_handler(request)
> File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp/web_app.py", line 366, in _handle
> resp = await handler(request)
> File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 106, in impl
> return await handler(request)
> File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp_session/**init**.py", line 152, in factory
> response = await handler(request)
> File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 96, in impl
> return await handler(request)
> File "/home/ubuntu/Desktop/caldera/app/service/auth_svc.py", line 68, in wrapped_function
> return await target_function(*args, **kwargs)
> File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp_jinja2/**init**.py", line 91, in wrapped
> context = await coro(*args)
> File "/home/ubuntu/Desktop/caldera/plugins/adversary/app/service/adversary_api.py", line 238, in planner
> techniques=con.get_techniques(),
> File "/home/ubuntu/Desktop/caldera/plugins/adversary/app/database/dao.py", line 24, in get_techniques
> return self.db.get_techniques(ids)
> File "/home/ubuntu/Desktop/caldera/plugins/adversary/app/database/mongo.py", line 59, in get_techniques
> return [self._map_technique(x) for x in self._query('technique', ids)]
> File "/home/ubuntu/Desktop/caldera/plugins/adversary/app/database/mongo.py", line 59, in
> return [self._map_technique(x) for x in self._query('technique', ids)]
> File "/home/ubuntu/.local/lib/python3.7/site-packages/pymongo/cursor.py", line 1189, in next
> if len(self.__data) or self._refresh():
> File "/home/ubuntu/.local/lib/python3.7/site-packages/pymongo/cursor.py", line 1104, in _refresh
> self.__send_message(q)
> File "/home/ubuntu/.local/lib/python3.7/site-packages/pymongo/cursor.py", line 982, in __send_message
> helpers._check_command_response(first)
> File "/home/ubuntu/.local/lib/python3.7/site-packages/pymongo/helpers.py", line 132, in _check_command_response
> raise NotMasterError(errmsg, response)
> pymongo.errors.NotMasterError: node is not in primary or recovering state

Is any solution to this issue?
