### ISSUE TITLE
no attribute config when loading module

### ISSUE THREAD

**Issue by mawiwillme** [mitre/adversary#33]
When trying to load the adversary plugin into caldera I get the following error:

`[caldera@localhost caldera]$ python3 server.py -E local
Traceback (most recent call last):
  File "server.py", line 99, in <module>
    plugin_modules = build_plugins(config['plugins'])
  File "server.py", line 84, in build_plugins
    modules.append(import_module('plugins.%s.hook' % plug))
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/caldera/test/caldera/plugins/adversary/hook.py", line 3, in <module>
    import plugins.adversary.app.config as config
  File "/home/caldera/test/caldera/plugins/adversary/app/config.py", line 6, in <module>
    from plugins.adversary.app.database.dao import Dao
  File "/home/caldera/test/caldera/plugins/adversary/app/database/dao.py", line 1, in <module>
    from plugins.adversary.app.database.mongo import Mongo
  File "/home/caldera/test/caldera/plugins/adversary/app/database/mongo.py", line 3, in <module>
    from plugins.adversary.app.database.model import Model
  File "/home/caldera/test/caldera/plugins/adversary/app/database/model.py", line 1, in <module>
    from plugins.adversary.app.utility.general import nested_get
  File "/home/caldera/test/caldera/plugins/adversary/app/utility/general.py", line 5, in <module>
    import plugins.adversary.app.config as config
AttributeError: module 'plugins.adversary.app' has no attribute 'config`

I don't know if it has to do with the way I'm loading the plugin, or if its a bug with the loading the plugin itself. I added the adversary tab under the plugins list in the yml file like so:

plugins:
  - adversary
  - stockpile
  - sandcat
  - gui
  - chain

**Comment by mawiwillme** [comment]
Just noticed a issue has already been opened for this
