### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by AngryOnigiri** [mitre/adversary#34]
Hello,

I've installed Caldera Server on Ubuntu 19.04 and my caldera agent ist also running and connected. 
But everytime I start an operation via the adversary plugin I get this error:

INFO:root:Bootstrapping rat with SYSTEM account
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp_session/__init__.py", line 152, in factory
    response = await handler(request)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 96, in impl
    return await handler(request)
  File "/home/ubuntu/.local/lib/python3.7/site-packages/aiohttp/web_urldispatcher.py", line 120, in handler_wrapper
    result = await result
  File "/home/ubuntu/Desktop/caldera/plugins/adversary/app/service/adversary_api.py", line 133, in rat_clients_checkin
    await self.api_logic.save_rat(token.session_info['_id'], data)
  File "/home/ubuntu/Desktop/caldera/plugins/adversary/app/service/api_logic.py", line 112, in save_rat
    mode=active_rats[key]['params']['rat_mode'],
KeyError: 'params'

Any ideas how to fix this?

**Comment by khyberspache** [comment]
Hey, I've started looking into this and have pulled it into a larger patch that will be pushed out (hopefully) later this week or early next week.

**Comment by ghost** [comment]
I believe this issue is resolved. @khyberspache or @AngryOnigiri can either of you confirm?

**Comment by ArtificialErmine** [comment]
@AngryOnigiri If the issue persists in the most recent version of Caldera, please let us know by re-opening this ticket or creating a new one. In the mean time, I'm closing this because it appears to have been resolved.
