### ISSUE TITLE
Adversary Plugin In Latest Stable Prevents Server.py from starting

### ISSUE THREAD

**Issue by tek911** [mitre/adversary#40]
I believe there is an issue with the adversary plugin's references to config in the latest stable. I have added the appropriate lines to my caldera/conf/local.yml as such:
`host: 0.0.0.0 
port: 8888
terminal_host: 0.0.0.0
terminal_port: 8880
sockets:
  - 8880
planner: plugins.stockpile.app.sequential
stores:
  - plugins/stockpile/payloads
  - plugins/adversary/payloads
plugins:
  - stockpile
  - sandcat
  - gui
  - chain
  - adversary
users:
  admin: admin`

When i start caldera (sudo python3 server.py) i am greeted with the following error:
`Traceback (most recent call last):
  File "server.py", line 111, in <module>
    plugin_modules = build_plugins(cfg['plugins'])
  File "server.py", line 96, in build_plugins
    modules.append(import_module('plugins.%s.hook' % plug))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/containeradmin/git/stable/caldera/plugins/adversary/hook.py", line 3, in <module>
    import plugins.adversary.app.config as config
  File "/home/containeradmin/git/stable/caldera/plugins/adversary/app/config.py", line 6, in <module>
    from plugins.adversary.app.database.dao import Dao
  File "/home/containeradmin/git/stable/caldera/plugins/adversary/app/database/dao.py", line 1, in <module>
    from plugins.adversary.app.database.mongo import Mongo
  File "/home/containeradmin/git/stable/caldera/plugins/adversary/app/database/mongo.py", line 3, in <module>
    from plugins.adversary.app.database.model import Model
  File "/home/containeradmin/git/stable/caldera/plugins/adversary/app/database/model.py", line 1, in <module>
    from plugins.adversary.app.utility.general import nested_get
  File "/home/containeradmin/git/stable/caldera/plugins/adversary/app/utility/general.py", line 5, in <module>
    import plugins.adversary.app.config as config
AttributeError: module 'plugins.adversary.app' has no attribute 'config'`

I believe the /home/containeradmin/git/stable/caldera/plugins/adversary/app/utility/general.py had a bad import reference, i can get past it by changing the config import to be 'from plugins.adversary.app import config' however i get errors about references to the filestore which i do not understand the app enough to know what the proper reference is or where the store variable should be imported from. Any assistance here is appreciated and I can button it up and put in a pull request for the fix. 

`containeradmin@BASE-EV1:~/git/stable/caldera$ sudo python3 server.py 
                  _//     _//                           
                  _//     _//                           
   _///   _//     _//     _//   _//    _/ _///   _//    
 _//    _//  _//  _// _// _// _/   _//  _//    _//  _// 
_//    _//   _//  _//_/   _//_///// _// _//   _//   _// 
 _//   _//   _//  _//_/   _//_/         _//   _//   _// 
   _///  _// _///_/// _// _//  _////   _///     _// _///
                                                        

Enter help or go to https://0.0.0.0:8888 in a browser
...Created user: admin:admin
Traceback (most recent call last):
  File "server.py", line 123, in <module>
    main(services=services, host=cfg['host'], port=cfg['port'], sockets=cfg['sockets'], users=cfg['users'])
  File "server.py", line 78, in main
    loop.run_until_complete(init(host, port, services, users))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "server.py", line 62, in init
    await attach_plugins(app, services)
  File "server.py", line 42, in attach_plugins
    await plugin(app, services)
  File "/home/containeradmin/git/stable/caldera/plugins/adversary/hook.py", line 56, in initialize
    config.initialize_settings(config_path='plugins/adversary/conf/config.ini', filestore_path=store)`

**Comment by taochengla** [comment]
I think there's import loop here. Error happens when "import plugins.adversary.app.config as config " appears second time. It's same problem describe [here on stackoverflow](https://stackoverflow.com/questions/12474374/infinite-loop-with-python-imports-looking-for-pythonic-way).  

Avoiding "from plugins.adversary.app.database.dao import Dao" in config.py may solve the problem.

**Comment by ArtificialErmine** [comment]
I can't seem to replicate this myself. There's a new patch with a bunch of bug fixes in it that's currently waiting to be pulled (https://github.com/mitre/adversary/pull/47). If the issue persists after that merge gets pulled in, let us know and we'll dig into the issue further.

**Comment by christophetd** [comment]
Hi @ArtificialErmine, 

Having the same issue with latest Caldera & Adversary, so I assume #47 didn't fix the issue. Here's how to reproduce:

- Clone Caldera (`git clone --recursive https://github.com/mitre/caldera`)
- Create a venv and enable it (`python3 -m venv venv && source venv/bin/activate`)
- Change `conf/local.yml` to load the adversary plugin:

```diff
diff --git a/conf/local.yml b/conf/local.yml
index be30bc9..e8eaad9 100644
--- a/conf/local.yml
+++ b/conf/local.yml
@@ -9,5 +9,6 @@ plugins:
   - sandcat
   - gui
   - chain
+  - adversary
 users:
   admin: admin
```

- Run Caldera

```
$ python server.py
DEBUG:root:Loading plugin: stockpile
DEBUG:root:Loading plugin: sandcat
DEBUG:root:Loading plugin: gui
DEBUG:root:Loading plugin: chain
DEBUG:root:Loading plugin: adversary
Traceback (most recent call last):
  File "server.py", line 85, in <module>
    plugin_modules = build_plugins(cfg['plugins'])
  File "server.py", line 35, in build_plugins
    modules.append(import_module('plugins.%s.hook' % plug))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/christophetd/tools/caldera/plugins/adversary/hook.py", line 3, in <module>
    import plugins.adversary.app.config as config
  File "/home/christophetd/tools/caldera/plugins/adversary/app/config.py", line 6, in <module>
    from plugins.adversary.app.database.dao import Dao
  File "/home/christophetd/tools/caldera/plugins/adversary/app/database/dao.py", line 1, in <module>
    from plugins.adversary.app.database.mongo import Mongo
  File "/home/christophetd/tools/caldera/plugins/adversary/app/database/mongo.py", line 3, in <module>
    from plugins.adversary.app.database.model import Model
  File "/home/christophetd/tools/caldera/plugins/adversary/app/database/model.py", line 1, in <module>
    from plugins.adversary.app.utility.general import nested_get
  File "/home/christophetd/tools/caldera/plugins/adversary/app/utility/general.py", line 5, in <module>
    import plugins.adversary.app.config as config
AttributeError: module 'plugins.adversary.app' has no attribute 'config'
```

Environment:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

$ source caldera/venv/bin/activate
$ python --version
Python 3.6.8
```

**Comment by christophetd** [comment]
Here's a working quickfix:

```diff
diff --git a/app/utility/general.py b/app/utility/general.py
index f96f3ed..d520345 100644
--- a/app/utility/general.py
+++ b/app/utility/general.py
@@ -2,7 +2,7 @@ import asyncio
 import json
 import os
 
-import plugins.adversary.app.config as config
+from .. import config
 from cryptography.fernet import Fernet
 
 """
```

Doing so enables Caldera to start up without crashing on the imports, although it fails for something else (which might be unrelated):

```
$ python server.py
DEBUG:root:Loading plugin: sandcat
DEBUG:root:Loading plugin: gui
DEBUG:root:Loading plugin: chain
DEBUG:root:Loading plugin: adversary
WARNING:root:Couldn't find clips module. Falling back to slower pyDatalog
DEBUG:root:Using an in-memory database: True
DEBUG:root:Uploaded files will be put in /tmp
DEBUG:file_svc:Downloaded files will come from ['plugins/sandcat/payloads', 'plugins/adversary/payloads']
DEBUG:root:Serving at http://127.0.0.1:8888
Traceback (most recent call last):
  File "server.py", line 100, in <module>
    main(services=services, host=cfg['host'], port=cfg['port'], users=cfg['users'])
  File "server.py", line 65, in main
    loop.run_until_complete(init(host, port, services, users))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "server.py", line 57, in init
    await attach_plugins(app, services)
  File "server.py", line 42, in attach_plugins
    await plugin(app, services)
  File "/home/christophetd/tools/caldera/plugins/adversary/hook.py", line 58, in initialize
    await setup_routes_and_services(app, services)
  File "/home/christophetd/tools/caldera/plugins/adversary/hook.py", line 14, in setup_routes_and_services
    await services.get('data_svc').reload_database(schema='plugins/adversary/conf/adversary.sql')
AttributeError: 'DataService' object has no attribute 'reload_database'
```

Let me know if you feel like this is worth a separate issue.

**Comment by dfirence** [comment]
Same issue for me and I cloned the repo this morning. :(

**Comment by ArtificialErmine** [comment]
@dfirence @christophetd @tek911 This turns out to be a rather interesting bug, since I can't seem to reproduce it on my system [windows, python 3.7.0] even following the exact steps provided by @christophetd. That being said, I think I found the root of the issue (what could be a circular import depending on how certain statements are handled), and put up a branch with fix, which hopefully will get pulled into master soon. Feel free to check out the patched branch and let me know if the problem persists - https://github.com/mitre/adversary/tree/load_data_fix.

@christophetd Your second error is also fixed here, though has a very different root. Recent changes to the main Caldera repository refactored the _reload_database_ method of the data service, and adversary hasn't been updated to reflect this quite yet (until this patch).

**Comment by ArtificialErmine** [comment]
Closing due to lack of activity. If the issue still persists, please re-open this issue or create a new one so we can resolve it.
