### ISSUE TITLE
Server conf.yml not present

### ISSUE THREAD

**Issue by ohmygord** [mitre/adversary#41]
When I start the CALDERA server I am able to login and I am presented with the following screen, so I'm confident I have connection. 
![image](https://user-images.githubusercontent.com/51379445/58967068-582cd000-87ab-11e9-8a2e-c53b5af3d73b.png)

However when I try to retrieve the **conf.yml file as per the instructions, I get a 404 error. (I am just set to listen on localhost, I cant even find the conf.yml file locally on my server) 

![image](https://user-images.githubusercontent.com/51379445/58967140-83afba80-87ab-11e9-8075-078b7573784e.png)

Could there have been an error in the setup process causing this? 
thanks

**Comment by ohmygord** [comment]
Im running this in Windows, i currently have %PATH% set with the appropriate Python folder. I also added the Caldera root directory. But still seeing the same issue. When starting Caldera i have been running it from the Root of the Caldera folder. Is there some other way i should be running it?

**Comment by Kerat** [comment]
Hello,
I have the exact same problem but on CentOS 7.
My caldera is in /opt/caldera and when I run `python3 server.py` from there I get the same error `AttributeError: module 'plugins.adversary.app' has no attribute 'config'`

Update:
I replaced `import plugins.adversary.app.config as config` on the third line of `hook.py` with 
`from plugins.adversary.app import config` and did the same with the fifth line of `app/utility/general.py `.
I also install ujson from pip (`pip3 install ujson`) because it was needed and missing from the requirements.

Caldera now runs and I can now get the file conf.yml from the server !
 But I can't access to the adversary part of the webGUI, I get an error 500
(url http://<my-server-ip>:8888/plugin/adversary/gui)
And when I run my cagent.exe from client with the debug option I can see thoses errors :  
```
Error 0xC00000FF - ERROR:caldera_agent.async_client:Uncaught exception retrieved in run_forever: Traceback (most recent call last):
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\async_client.py", line 49, in run_forever
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\async_client.py", line 63, in fail_pending
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 165, in jobs
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 72, in rest
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 104, in _raw_rest
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 44, in start
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 123, in _rest
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 217, in api
  File "C:\Program Files\Python35\lib\asyncio\futures.py", line 381, in __iter__
  File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 310, in _wakeup
  File "C:\Program Files\Python35\lib\asyncio\futures.py", line 294, in result
  File "C:\Program Files\Python35\lib\concurrent\futures\thread.py", line 55, in run
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 224, in urlread
  File "C:\Program Files\Python35\lib\urllib\request.py", line 163, in urlopen
  File "C:\Program Files\Python35\lib\urllib\request.py", line 466, in open
  File "C:\Program Files\Python35\lib\urllib\request.py", line 484, in _open
  File "C:\Program Files\Python35\lib\urllib\request.py", line 444, in _call_chain
  File "C:\Program Files\Python35\lib\urllib\request.py", line 1282, in http_open
  File "C:\Program Files\Python35\lib\urllib\request.py", line 1254, in do_open
  File "C:\Program Files\Python35\lib\http\client.py", line 1107, in request
  File "C:\Program Files\Python35\lib\http\client.py", line 1147, in _send_request
  File "C:\Program Files\Python35\lib\http\client.py", line 1084, in putheader
ValueError: Invalid header value b'AUTH=<head>\n    <title>Login | Access</title>\n\t<link rel="shortcut icon" type="image/png" href="/gui/img/favicon.png"/>\n\ConsoleCtrlHandler function failedTraceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\win32\lib\win32serviceutil.py", line 446, in _DebugCtrlHandler
OSError: [Errno 22] Invalid argument
t<link rel="stylesheet" href="/gui/css/shared.css" type="text/css">\n\t<link rel="stylesheet" href="/gui/css/basic.css" type="text/css">\n\t<link rel="stylesheet" href="/gui/css/login.css" type="text/css">\n</head>\n\n<form action="/enter" method="POST">\n\t<div class="login">\n\t\t<div class="login-screen">\n\t\t\t<div class="app-title">\n\t\t\t\t<h3 style="color: black">Access</h3>\n\t\t\t</div>\n\n\t\t\t<div class="login-form">\n\t\t\t\t<div class="control-group">\n\t\t\t\t<input type="text" class="login-field" value="" placeholder="username" name="username">\n\t\t\t\t<label class="login-field-icon fui-user" for="login-name"></label>\n\t\t\t\t</div>\n\n\t\t\t\t<div class="control-group">\n\t\t\t\t<input type="password" class="login-field" value="" placeholder="password" name="password">\n\t\t\t\t<label class="login-field-icon fui-lock" for="login-pass"></label>\n\t\t\t\t</div>\n\n                <input type="submit" value="Log in" class="button-success" >\n\t\t\t    <br>\n                <p style="font-size:12px;color:grey">Trouble logging in?<br>Clear your cookies and try again.<br>For the best experience, use Chrome</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</form>\n<script>\n    document.cookie.split(";").forEach(function(c) { document.cookie = c.replace(/^ +/, "").replace(/=.*/, "=;expires=" + new Date().toUTCString() + ";path=/"); });\n</script>'
```

**Comment by Kerat** [comment]
UPDATE 2:
I tried with SSL plugin and now get this error when trying `cagent.exe debug`:
```
c:\Program Files\cagent>cagent.exe debug
Debugging service cagent - press Ctrl+C to stop.
Info 0x400000FF - Created WinSvcLogHandler
Info 0x40001002 - The cagent service has started.
Error 0xC00000FF - ERROR:root:Task exception was never retrieved
future: <Task finished coro=<CalderaAgent.send_clients() done, defined at C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\agent.py:59> exception=RequestFailed()>
Traceback (most recent call last):
File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 240, in _step
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\agent.py", line 61, in send_clients
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 173, in clients
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 72, in rest
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 104, in rawrest
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 44, in start
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 143, in _rest
caldera_agent.rest_api.RequestFailed
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:root:Task exception was never retrieved
future: <Task finished coro=<Client.heartbeat() done, defined at C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\async_client.py:38> exception=RequestFailed()>
Traceback (most recent call last):
File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 240, in _step
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\async_client.py", line 40, in heartbeat
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 192, in stay_alive
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 72, in rest
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 104, in rawrest
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 44, in start
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 143, in _rest
caldera_agent.rest_api.RequestFailed
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503 
```
So the connection seems to be good but I can't locate the problem on the server side.
I have no logs on the server. Just the startup messages and admin connections.
(I put debug in local.yml)

**Comment by amonyphily** [comment]
up please

**Comment by ArtificialErmine** [comment]
Sorry about the delay on this. It turns out some changes to the base Caldera had unexpected side effects for adversary mode. I've written a patch for this and some other bugs that is currently awaiting merge (https://github.com/mitre/adversary/pull/47), which should fix the issue.

**Comment by ArtificialErmine** [comment]
If this issue still exists, feel free to reopen this ticket or create a new one. Otherwise, it appears that #47 fixed root of this issue.
