### ISSUE TITLE
Error while loading adversary plugin - mongoengine.errors.NotRegistered: `TechniqueMapping`

### ISSUE THREAD

**Issue by BernaldoPenasAntelo** [mitre/adversary#53]
Hi:
I'm getting this error

DEBUG:root:Loading plugin: stockpile
DEBUG:root:Loading plugin: sandcat
DEBUG:root:Loading plugin: gui
DEBUG:root:Loading plugin: chain
DEBUG:root:Loading plugin: adversary
Traceback (most recent call last):
  File "server.py", line 85, in <module>
    plugin_modules = build_plugins(cfg['plugins'])
  File "server.py", line 35, in build_plugins
    modules.append(import_module('plugins.%s.hook' % plug))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/caldera/plugins/adversary/hook.py", line 4, in <module>
    from plugins.adversary.app.service.adversary_api import AdversaryApi
  File "/opt/caldera/plugins/adversary/app/service/adversary_api.py", line 10, in <module>
    import plugins.adversary.app.authentication as auth
  File "/opt/caldera/plugins/adversary/app/authentication.py", line 5, in <module>
    from plugins.adversary.app.engine.objects import SiteUser
  File "/opt/caldera/plugins/adversary/app/engine/objects.py", line 582, in <module>
    class CodedStep(ExtrovirtsDocument):
  File "/opt/caldera/plugins/adversary/app/engine/database.py", line 62, in __new__
    return super().__new__(mcs, name, bases, dct)
  File "/usr/local/lib/python3.7/dist-packages/mongoengine/base/metaclasses.py", line 364, in __new__
    meta['index_specs'] = new_class._build_index_specs(meta['indexes'])
  File "/usr/local/lib/python3.7/dist-packages/mongoengine/base/document.py", line 755, in _build_index_specs
    unique_indices = cls._unique_with_indexes()
  File "/usr/local/lib/python3.7/dist-packages/mongoengine/base/document.py", line 915, in _unique_with_indexes
    field.document_type != cls):
  File "/usr/local/lib/python3.7/dist-packages/mongoengine/fields.py", line 674, in document_type
    resolved_document_type = get_document(self.document_type_obj)
  File "/usr/local/lib/python3.7/dist-packages/mongoengine/base/common.py", line 31, in get_document
    """.strip() % name)
mongoengine.errors.NotRegistered: `TechniqueMapping` has not been registered in the document registry.
            Importing the document class automatically registers it, has it
            been imported?

Can you help me to debug it. Thanks in advance

**Comment by dkrdini** [comment]
Hi, @BernaldoPenasAntelo As a workaround in /opt/caldera/plugins/adversary/app/engine/objects.py move the class TechniqueMapping before class CodedStep where it is referenced. Hope this helps.

**Comment by ArtificialErmine** [comment]
@BernaldoPenasAntelo I can't seem to replicate this locally at the moment. Can you verify that the issue is still present in the most recent iteration of the code, and whether or not dkrdini's solution worked for you?

**Comment by ArtificialErmine** [comment]
Closing due to inactivity. If the issue persists, feel free to re-open this ticket or create a new one.
